### ISSUE TITLE
Translation doesn't appear

### ISSUE THREAD

**Issue by darnn** [xinebf/google-translate-for-goldendict#1]
Hi!
I can't seem to get this to work, either in Goldendict or just from the command line. 
I have Python 3.7 installed, and have installed requests.
In Goldendict, I get the following error:
Query error: The program has returned exit code 1. Traceback (most recent call last): File "D:\gt\googletranslate.py", line 43, in <module> gtrans() File "D:\gt\googletranslate.py", line 37, in gtrans print(result.encode('gbk', 'ignore').decode('gbk')) File "D:\Python\Python37-32\lib\encodings\cp1255.py", line 19, in encode return codecs.charmap_encode(input,self.errors,encoding_table)[0] UnicodeEncodeError: 'charmap' codec can't encode characters in position 33-34: character maps to <undefined>

**Comment by xinebf** [comment]
I am using Python 3.7 on Windows 10, there is no problem with the translation of Goldendict, which one is the target language you are using.

**Comment by darnn** [comment]
Hebrew. I'm using Windows 7 SP1, and the latest Windows build of the Goldendict beta (1.5.0-RC2-311-g15062f7).

**Comment by darnn** [comment]
Wait, so, I should clarify: I get the above error if I try translating into Chinese (zh-CN). When I try translating into Hebrew (he-IL), I only get the original term I was trying to translate:
![gt-he-il](https://user-images.githubusercontent.com/19672444/45536661-cccd7200-b80a-11e8-8ff3-930323c48c9c.png)

**Comment by xinebf** [comment]
You can replace the two gbk with **cp1255** in line 37 of googletranslate.py.
```
print(result.encode('cp1255', 'ignore').decode('cp1255'))
```

**Comment by darnn** [comment]
Ahh, it works! Thank you! I also have a different bug report (or feature request, depending on how you look at it), but I'll open a separate issue.
