### ISSUE TITLE
'asyncio' has no attribute 'run'

### ISSUE THREAD

**Issue by andradadad** [xinebf/google-translate-for-goldendict#13]
`Query error: The program has returned exit code 1. Traceback (most recent call last): File "C:\googletranslate.py", line 132, in <module> asyncio.run(get_translation()) AttributeError: module 'asyncio' has no attribute 'run'`

Also, can you tell me how to separate the original line to the translate with a double space? I tried looking into the script and couldn't find it, I think it's much more comprehensible to have them separated with a blank line inbetween than just a /r/n.

**Comment by xinebf** [comment]
Update Python 3 to Python 3.7+

**Comment by xinebf** [comment]
Change [Line 100](https://github.com/xinebf/google-translate-for-goldendict/blob/4277fd0998d49092a9c7facea4f409b62c0946a6/googletranslate.py#L100) to:

```
result = get_result(result, resp_alt) + '\n \n'
```

Change [Line 104](https://github.com/xinebf/google-translate-for-goldendict/blob/4277fd0998d49092a9c7facea4f409b62c0946a6/googletranslate.py#L104) to:

```
result += '^_^: Translate {} To {}\n{}\n \n'.format(resp[2], target_language, query_string)
```

**Comment by andradadad** [comment]
And how do I remove the entire line `^_^: Translate {} To {}`

I want the **Original**+/n/n+**translated**

**Comment by xinebf** [comment]
Use this [commit](https://github.com/xinebf/google-translate-for-goldendict/blob/d0d2f01a05f9e044dfe597667b42d681f9fcdef0/googletranslate.py) and replace [Line 26](https://github.com/xinebf/google-translate-for-goldendict/blob/d0d2f01a05f9e044dfe597667b42d681f9fcdef0/googletranslate.py#L26) with

```
result = result + '{}\n \n'.format(sys.argv[2])
```
