### ISSUE TITLE
Query error

### ISSUE THREAD

**Issue by CirrusG** [xinebf/google-translate-for-goldendict#15]
你好,

![image](https://user-images.githubusercontent.com/54894516/71758441-a606d500-2e6d-11ea-86da-34be6a906bb7.png)

错误如图显示。
不知道哪里出了问题，是否可以给个解答？
谢谢！

**Comment by xinebf** [comment]
参考 #1

[修改 125 行](https://github.com/xinebf/google-translate-for-goldendict/blob/e692c3409014145c2d876df03aaff94df79729c6/googletranslate.py#L125)
```
    gtrans = GoogleTranslate(result_code='cp1252')
```

**Comment by CirrusG** [comment]
按照你说的步骤修改后，可以使用了。不过只能中文翻译为英文，并且翻译后并没有原文对照。

如图所示。

中文翻译为英文
![image](https://user-images.githubusercontent.com/54894516/71769031-e9068e00-2ee9-11ea-96e5-7809d94889ee.png)

英文翻译为中文（未成功）
![image](https://user-images.githubusercontent.com/54894516/71769035-f3288c80-2ee9-11ea-8fde-bb975f6bb3da.png)

希望可以得解决。
谢谢！

**Comment by xinebf** [comment]
[CP-1252](https://en.wikipedia.org/wiki/Windows-1252) 不支持中文字符

你可以试试把 `result_code='cp1252'` 改为 `result_code='utf-8'`

**Comment by CirrusG** [comment]
修改后结果如下，这会不会跟我的电脑系统是英文的有关呢？

![image](https://user-images.githubusercontent.com/54894516/71783421-89c18000-2fb4-11ea-8c06-90c9406f3c0b.png)

**Comment by darnn** [comment]
in case it helps, i'm attaching the file i'm using, which i've modified to translate into hebrew, and which doesn't produce those errors:
[googletranslate.zip](https://github.com/xinebf/google-translate-for-goldendict/files/4023779/googletranslate.zip)

**Comment by xinebf** [comment]
这个问题和 Goldendict 有关，在中文的 Windows 系统上面，只能输出使用 gbk 编码的字符，从你截图的报错信息来看是只能输出 cp1252 编码的字符，超出此字符编码范围就会报错，具体怎么解决，现在我也没整明白

**Comment by CirrusG** [comment]
> 
> 
> 这个问题和 Goldendict 有关，在中文的 Windows 系统上面，只能输出使用 gbk 编码的字符，从你截图的报错信息来看是只能输出 cp1252 编码的字符，超出此字符编码范围就会报错，具体怎么解决，现在我也没整明白

唔，或许是由于软件版本问题。
这是我下载的Goldendict版本号。
![image](https://user-images.githubusercontent.com/54894516/71798731-26ba0280-3021-11ea-8a13-a3e1681c36ac.png)

**Comment by CirrusG** [comment]
> 
> 
> in case it helps, i'm attaching the file i'm using, which i've modified to translate into hebrew, and which doesn't produce those errors:
> [googletranslate.zip](https://github.com/xinebf/google-translate-for-goldendict/files/4023779/googletranslate.zip)

Thanks! But the problem still exists. 
As shown below
![image](https://user-images.githubusercontent.com/54894516/71799047-2a9a5480-3022-11ea-8e08-04087a3ec133.png)
The developer considers the problem is related to Goldendict.

**Comment by xinebf** [comment]
你截图中的版本和我使用的版本是一致的，有上面所说的问题。

**Comment by hufenglin** [comment]
这个是goldendict版本的问题吗？能够快点解决就好啦

**Comment by xinebf** [comment]
使用这个 [commit](https://github.com/xinebf/google-translate-for-goldendict/blob/1240b71a673a2f7a01ab835e6ceadcac14f7fd68/googletranslate.py), 在设置 Goldendict 时将 `纯文本` 改为 `Html`, 并在 `googletranslate.py` 中[修改](https://github.com/xinebf/google-translate-for-goldendict/blob/1240b71a673a2f7a01ab835e6ceadcac14f7fd68/googletranslate.py#L139):
```
gtrans = GoogleTranslate(result_type='html')
```
就能正常显示中文了.

**Comment by wangran915** [comment]
谢谢分享，使用中有2个问题希望您能帮忙解答下：
1：显示的字太小了，不知道能否调整字体大小及颜色？
2：能否调用音频？
非常期待您的回复，谢谢！

**Comment by wangran915** [comment]
请问怎么能只显示单一的翻译结果，把定义和其他频率的翻译给去掉？

**Comment by xinebf** [comment]
@wangran915 
字体大小, Goldendict 工具栏中有缩放按键. 也可以改 [CSS](https://github.com/xinebf/google-translate-for-goldendict/blob/eed093fdf5556ed181f8fc979439bd670d06c59c/googletranslate.py#L94) 的部分.
音频, 没有加入的计划.
去掉定义, [修改](https://github.com/xinebf/google-translate-for-goldendict/blob/eed093fdf5556ed181f8fc979439bd670d06c59c/googletranslate.py#L149) `gtrans = GoogleTranslate(result_type='html', definitions_en=False)`

**Comment by wangran915** [comment]
调整了CSS，字体和定义已经按您说的搞好了。就不知道以下部分是否也能去除？感谢您的回复！祝您生活愉快！
[image: image.png]

xinebf <notifications@github.com> 于2020年2月4日周二 下午1:42写道：

**Comment by wangran915** [comment]
例：
^_^: Translate en To zh-CN
Translations
翻译

以下部分是否也能去除？
=========
0_0: Translations of Translations
# 名.
翻译: translation, interpretation, rendering, rendition, version, decipherment
翻: turn, translation, turnover
解答: answer, solution, explanation, response, reply, respond
来自The Little Dict

王然 <wr92yq@gmail.com> 于2020年2月4日周二 下午4:59写道：

**Comment by xinebf** [comment]
@wangran915 
分别移除 [124](https://github.com/xinebf/google-translate-for-goldendict/blob/eed093fdf5556ed181f8fc979439bd670d06c59c/googletranslate.py#L124), [128](https://github.com/xinebf/google-translate-for-goldendict/blob/eed093fdf5556ed181f8fc979439bd670d06c59c/googletranslate.py#L128) 两行

**Comment by wangran915** [comment]
124:               self.get_result(resp_alt)
128:               self.get_result(resp)
我这边显示这两行是这个,但删除后查单词就报错, 查句子就只显示原句.

xinebf <notifications@github.com> 于2020年2月23日周日 下午7:29写道：
