### ISSUE TITLE
Errrrrrrrrror Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by DatHoang29** [xinebf/google-translate-for-goldendict#16]
How to fix this error `@@
![Screenshot from 2020-02-05 11-01-08](https://user-images.githubusercontent.com/46701740/73809807-fa072f80-4806-11ea-860a-57b04e52275c.png)

**Comment by kuwylsr** [comment]
i have the same problem

**Comment by gary02** [comment]
It seem that it cause by the  google translate server responsing a error page: ```This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsibles```

**Comment by xinebf** [comment]
fixed.  3e9d80136f499b79cf6e061d7243cc33ab9df619

**Comment by vipzrx** [comment]
@xinebf 我使用 1.3.9的版本,还是会报这个错误

命令行 和goldendict中都提示

来自Google收起文章
Errrrrrrrrror: Expecting value: line 1 column 1 (char 0)

使用的命令参数 
`
C:\Users\kk\AppData\Local\Programs\Python\Python39\python.exe -m googletranslate  -p 127.0.0.1:1080 zh-CN %GDWORD% -s "translate.google.cn"
`
