### ISSUE TITLE
On entries with machine translation and dictionary translation, only machine translation is displayed

### ISSUE THREAD

**Issue by darnn** [xinebf/google-translate-for-goldendict#2]
Hey. So. If you look up individual words or phrases in Google Translate, it not only provides its own machine translation. It also has built in dictionaries, which occasionally feature several translations for the same word/phrase, which are sometimes outright different from (and more accurate than) the machine translation.
A couple of examples:
![gt-window](https://user-images.githubusercontent.com/19672444/45538350-7f9fcf00-b80f-11e8-886e-96fd481ac82b.png)

![gt-pilot](https://user-images.githubusercontent.com/19672444/45538360-862e4680-b80f-11e8-97ca-4b00bf0f528a.png)

(For instance, in the second example, the machine translation is a literal translation of the words "pilot" and "light", but the dictionary translations are actual translations of the entire phrase.)

Is there a way to get GT for Goldendict to display the dictionary translation as well?

**Comment by xinebf** [comment]
This feature will be added later.

**Comment by darnn** [comment]
Great! Thank you!

**Comment by xinebf** [comment]
@darnn You can try the latest commit. 87c7a2d

**Comment by darnn** [comment]
It works! Thank you so much! Feel free to close this.
