### ISSUE TITLE
程序错误

### ISSUE THREAD

**Issue by xiaotianxt** [xinebf/google-translate-for-goldendict#20]
![image](https://user-images.githubusercontent.com/17041194/80185280-ac000c00-863e-11ea-8812-3debb3060ede.png)
根据您的说明改正后程序运行报错~

**Comment by xinebf** [comment]
替换值的时候，引号需要保留，不能去掉

**Comment by xiaotianxt** [comment]
十分感谢！当时脑子抽了后来修好了！
