### ISSUE TITLE
查询报错

### ISSUE THREAD

**Issue by qpmcool** [xinebf/google-translate-for-goldendict#21]
查询错误：程序返回，退出代码为 1. Traceback (most recent call last): File "D:\GoldenDict\googlet\googletranslate\googletranslate.py", line 20, in <module> from .googletranslatetk import Token ImportError: attempted relative import with no known parent package

**Comment by xinebf** [comment]
使用方式有点不对, 用下面命令安装的,
 
```
pip install google-translate-for-goldendict
```

命令行需要填成:

```
python -m googletranslate.googletranslate zh-CN %GDWORD%
```

**Comment by qpmcool** [comment]
已经可以了。非常感谢。觉得应该更新一下readme。
