### ISSUE TITLE
line 39 syntax error

### ISSUE THREAD

**Issue by liushawulan** [xinebf/google-translate-for-goldendict#25]
url = f'https://{self.http_host}/translate_a/single?client=webapp&sl=auto&tl={tl}&hl=en&dt=at&dt=bd&dt=ex&' \
              f'dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=sos&dt=ss&dt=t&ssel=0&tsel=0&kc=1&tk={tk}&q={qry}'
报这句语法错误。

**Comment by xinebf** [comment]
提示这一句有错误，可以先检查一下 Python 版本是不是在 3.7 以上.

**Comment by liushawulan** [comment]
版本是3.8，可能是其他错误吧，暂时先放着，应该是我自己的问题。：）
