### ISSUE TITLE
查询结果提示：Errrrrrrrrror: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by wdcoding** [xinebf/google-translate-for-goldendict#31]
Python 3.7.9    google-translate-for-goldendict-1.3.5
查询结果提示：Errrrrrrrrror: check_hostname requires server_hostname

**Comment by wdcoding** [comment]
解决了，忘了配置代理，尴尬^_^

**Comment by ACupofAir** [comment]
我配了这个代理也有问题欸，wikipedia能正常出，但这个google翻译报这个问题；我怀疑是机器人检测的问题，因为goldendict自带的google翻译会跳转机器人判别
