### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by jasoworld** [xinebf/google-translate-for-goldendict#32]
Errrrrrrrrror: HTTPSConnectionPool(host='translate.google.cn', port=443): Max retries exceeded with url: /translate_a/single?client=webapp&sl=auto&tl=zh-CN&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=sos&dt=ss&dt=t&ssel=0&tsel=0&kc=1&tk=818253.705791&q=%25GDWORD%25 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

帮忙看看如何解决,公司网络,需要SSL认证

**Comment by jasoworld** [comment]
问题解决，参见https://blog.csdn.net/iKaChu/article/details/106787413

**Comment by username0occupied** [comment]
My solution is upgrading my system openssl(version 1.1)
