### ISSUE TITLE
python调用问题

### ISSUE THREAD

**Issue by liushawulan** [xinebf/google-translate-for-goldendict#34]
最近瞎安装command line tools, 发现翻译程式调用的不是系统python, 而是xcode下的。我删除了command line tool, 但是goldendict报错
![image](https://user-images.githubusercontent.com/38710354/126448992-26ef9aca-97ec-4b67-aa70-5dc5c5589215.png)
尽管直接在iterm2中
![image](https://user-images.githubusercontent.com/38710354/126449045-00419713-408b-452d-8925-129c6295c72c.png)
这种问题请问老哥怎么办？
谢谢。

**Comment by liushawulan** [comment]
重新安装了command line tool, 又回到老提示：
![image](https://user-images.githubusercontent.com/38710354/126451977-ca5dae91-783f-4bf4-be03-bb7b53c2cc9a.png)
起初goldendict调用的python3 好好的。都是这两天瞎安装。

**Comment by xinebf** [comment]
在 python -m googletranslate ... 这个命令中的 python 换成安装 python 的完整路径试试.
终端中输入 which python3 可以看 python3 在哪个路径下.

**Comment by liushawulan** [comment]
> which python3

谢谢老哥，按照你的提示，我用 /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 替代python3, 就可以了。：）
