### ISSUE TITLE
翻译内容与网页版不一致

### ISSUE THREAD

**Issue by DivingWhale** [xinebf/google-translate-for-goldendict#36]
goldendict内是这样的
![image](https://user-images.githubusercontent.com/49824897/131648299-64983502-073e-49b4-8636-e7c6bc1ef496.png)
而在网页上是这样的
![image](https://user-images.githubusercontent.com/49824897/131648432-2a314090-32be-48b2-aaad-19cdf4b3659e.png)
翻译出来的内容总是非常奇怪，似乎是因为在将翻译提交给谷歌的时候添加了不必要的换行符导致的

**Comment by DivingWhale** [comment]
我做了测试，如果在网页上翻译的时候给每个换行处手动敲一下回车，就和goldendict里得到的结果一模一样
![image](https://user-images.githubusercontent.com/49824897/131649337-fc57fbf1-bb7a-4100-a404-398f0b56ae0e.png)
就像图中这样，我在每行结束的时候都手动加了一个回车，就和下图的软件内结果一致
![image](https://user-images.githubusercontent.com/49824897/131649468-811dfdd0-5e19-4dd5-8ed7-657bbb1776ff.png)

**Comment by xinebf** [comment]
从 goldendict 传过来的参数, 回车好像会丢失.
刚才对比了一下和 google 翻译网页版的结果, 不知道什么时候开始的, 的确会有点不一样了, 我找时间检查一下看看是什么问题.
