### ISSUE TITLE
Translation results are different from Google Translate via web browser

### ISSUE THREAD

**Issue by ghost** [xinebf/google-translate-for-goldendict#38]
The Translation results are different with those on Google Translate website.

I also configured "Translate Shell" on GoldenDict and the translations are different. Theoretically they should be the same since they come from Google, but something is happening.

Translations using "Translate Shell" are the same as on Google Translate via a web browser. 

Translations provided by " google-translate-for-goldendict" are of lower quality. The definitions, synonyms, etc. work perfectly. The only problem is the poor quality of translation and that they do not match those provided by Google:

![grafik](https://user-images.githubusercontent.com/58692066/145669951-8acac043-3efc-47cf-80ff-401ab11b3e66.png)

![grafik](https://user-images.githubusercontent.com/58692066/145669970-d800894e-adf4-4a29-a520-df22d6b7a9d4.png)

![grafik](https://user-images.githubusercontent.com/58692066/145670055-40b00d33-0119-4029-9a06-dfbadd79fb3b.png)

_----------
Instructions to install "Translate Shell" on GoldenDict are here: 
https://superuser.com/questions/1319632/how-to-add-online-dictionaries-like-google-translate-to-goldendict

**_I hope the issue could be solved ! Thanks for your great work !_**

_"Translate Shell" has a very ugly and disfunctional display of results. Your script is much better because the results are displayed beautifully ! The only problem currently is that translation's quality is low. Was the service provider changed ?_

**Comment by xinebf** [comment]
Thank you very much for your feedback, I will check the program some time.

**Comment by xinebf** [comment]
[fixed](https://github.com/xinebf/google-translate-for-goldendict/releases/tag/v1.3.8).
