### ISSUE TITLE
Errrrrrrrrror: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by moses3415** [xinebf/google-translate-for-goldendict#39]
之前使用都没问题，今天突然开始报错：Errrrrrrrrror: Expecting value: line 1 column 1 (char 0)
图片：
![image](https://user-images.githubusercontent.com/56709195/150665446-4d9fb16f-64d7-46a2-b194-f81a0e2f39e0.png)

**Comment by moses3415** [comment]
已经恢复了

**Comment by vipzrx** [comment]
@moses3415 你的是怎么恢复的? 没有管他,过段时间就自己好了吗?
