### ISSUE TITLE
在python中可用, 在goldendict中报错: 查询错误：程序返回，退出代码为 9009.

### ISSUE THREAD

**Issue by canNotCtrlSelf** [xinebf/google-translate-for-goldendict#45]
我的系统是win11, python版本是3.11.0

尝试了网友说的, 在系统变量中添加python的路径, 但是依旧报这个错误

**Comment by Ethkuil** [comment]
可以贴下 GoldenDict 里用的命令行看看

**Comment by canNotCtrlSelf** [comment]
> 可以贴下 GoldenDict 里用的命令行看看

我就切换了一下代理的状态, 问题解决了
