### ISSUE TITLE
吞掉原文的回车，以及划词翻译的最后一个标点

### ISSUE THREAD

**Issue by shuwai** [xinebf/google-translate-for-goldendict#6]
Hi!
首先感谢作者的辛勤付出以及无私分享。我尝试过很多方法在GoldenDict中使用Google translate，包括添加网络词典，但只有这一个程序是奏效的。

我在使用过程中发现选取长句翻译时，发现有以下问题。（附图）

1. 程序会吞掉句子（包括原文以及翻译结果）中的回车。在主窗口中会只保留一个回车，而在Ctrl+C+D划词翻译窗口会吞掉所有回车。
2. 另外，划词翻译会吞掉最后一个标点。而在主窗口中则不会发生这种情况。

而我不知这是GD本身的bug还是这个小程序的原因，希望您可以留意这个小问题。:)
![2019-02-20_15-12-54](https://user-images.githubusercontent.com/42209556/53073430-f362a800-3522-11e9-8f96-af3ec0de3333.png)

**Comment by xinebf** [comment]
对，有这两个问题，这是由于 goldendict 导致的。
