### ISSUE TITLE
A small question about your source code

### ISSUE THREAD

**Issue by zhjuly** [xinebf/google-translate-for-goldendict#8]
Hi xinebf,
It is very grateful for your code.
But I have a small question about the line 84 code "if resp[2] == target_language", I think the sign of equality should be the sign of inequality.

**Comment by xinebf** [comment]
resp[2] is source language.
```
if resp[2] == target_language:
    ...
```
When the source language is equal to the target language, the source language is translated into an alternate language

**Comment by zhjuly** [comment]
> resp[2] is source language.
> 
> ```
> if resp[2] == target_language:
>     ...
> ```
> 
> When the source language is equal to the target language, the source language is translated into an alternate language

Well, thanks for your explanation.
